### ISSUE TITLE
Missing .nvmrc file causes theme provisioning to fail

### ISSUE THREAD

**Issue by banoodle** [kanopi/toland#17]
On line 70 of kanopi/drupal-starter's [install-theme-tools docksal script](https://github.com/kanopi/drupal-starter/blob/main/.docksal/commands/install-theme-tools), an .nvmrc file is loaded. 

Because Toland lacks this file, the install-theme-tools doesn't complete the theme provisioning.

Adding a file to the root of toland called .nvmrc fixes the problem.

I think the contents of .nvmrc should be just one line: `v10.16.3` - but I'm not sure about this. Testing with this value doesn't throw any errors, but I also don't have the fin gulp command fulling working (so maybe this isn't the right version).

**Comment by paulsheldrake** [comment]
have added the file
