### ISSUE TITLE
fin gulp watch doesn't do anything

### ISSUE THREAD

**Issue by banoodle** [kanopi/toland#18]
When I run `fin gulp watch` it looks like the process is running, but any changes to scss or js are just ignored.

![Screen Shot 2022-11-01 at 6 54 51 PM](https://user-images.githubusercontent.com/7685811/199376464-8b248dc7-287f-49c9-8fbc-edf02bb5cc78.png)

**Comment by paulsheldrake** [comment]
Switched watch to use polling method so it works in docker
